import os

from dotenv import load_dotenv

load_dotenv()

BALLDONTLIE_API_KEY = os.getenv("BALLDONTLIE_API_KEY")
KAFKA_BOOTSTRAP_SERVERS = os.getenv("KAFKA_BOOTSTRAP_SERVERS")
KAFKA_TOPIC_NBA_GAME_SCORES = os.getenv("KAFKA_TOPIC_NBA_GAME_SCORES")
KAFKA_TOPIC_NBA_TEAMS = os.getenv("KAFKA_TOPIC_NBA_TEAMS")
